[package]
name = "tolstack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
rand_xoshiro = "0.6"
statrs = "0.15.0"
rayon = "1.5"
num_cpus = "1.13"

[profile.release]
lto = true
